// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 12.0.0.0
//  
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DLLTemp : DLLTempBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using NLog;\r\nusing NTCL.Model.Domain;\r\nusing System;\r\nusing System.Collections.Ge" +
                    "neric;\r\nusing System.Data.Entity;\r\nusing System.Data.SqlClient;\r\nusing System.Li" +
                    "nq;\r\nusing System.Text;\r\nusing System.Text.RegularExpressions;\r\n\r\nnamespace ");
            
            #line 16 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 18 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(@"
    {
        #region Fields
        private static Logger logger = NLog.LogManager.GetCurrentClassLogger();
        private DateTime now = DateTime.Now;
        #endregion

        #region Property
        private List<object> param { get; set; }
        #endregion

        #region Constructor
        public ActivityBoardDao()
        {
            param = new List<object>();
        }
        #endregion

        #region Method
        public bool Add(");
            
            #line 37 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            using(");
            
            #line 39 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 39 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write("())\r\n            {\r\n                using(var dbContextTransaction = db.Database." +
                    "BeginTransaction())\r\n\t            {\r\n\t\t            try\r\n                    {\r\n " +
                    "                       #region Table Content\r\n                        string con" +
                    "tentId = Guid.NewGuid().ToString();\r\n                        param.Add(new SqlPa" +
                    "rameter(\"@ContentID\", contentId));\r\n                        param.Add(new SqlPar" +
                    "ameter(\"@ContentTypeID\", ContentTypeModel.CONTENT_TYPE_測試用));\r\n                 " +
                    "       param.Add(new SqlParameter(\"@Name\", model.Name ?? (object)DBNull.Value));" +
                    "\r\n                        param.Add(new SqlParameter(\"@Description\", model.Descr" +
                    "iption ?? (object)DBNull.Value));\r\n                        param.Add(new SqlPara" +
                    "meter(\"@IsPublish\", model.IsPublic));\r\n                        param.Add(new Sql" +
                    "Parameter(\"@OpenTime\", model.OpenTime));\r\n                        param.Add(new " +
                    "SqlParameter(\"@CloseTime\", model.CloseTime));\r\n                        param.Add" +
                    "(new SqlParameter(\"@Creator\", model.Updater ?? \"system\"));\r\n                    " +
                    "    param.Add(new SqlParameter(\"@Updater\", model.Updater ?? \"system\"));\r\n       " +
                    "                 db.Database.ExecuteSqlCommand(@\" \r\n                            " +
                    "INSERT INTO Content(ID, ContentTypeID, Name, Description, IsPublish, OpenTime, C" +
                    "loseTime,  Creator, CreateTime, Updater, UpdateTime)\r\n                          " +
                    "  VALUES (@ContentID, @ContentTypeID, @Name, @Description, @IsPublish, @OpenTime" +
                    ", @CloseTime , @Creator, GETDATE(), @Updater, GETDATE());\",\r\n                   " +
                    "         param.ToArray());\r\n\r\n                        #endregion\r\n\r\n            " +
                    "            #region Table ActivityBoard\r\n                        string activity" +
                    "BoardId = Guid.NewGuid().ToString();\r\n                        param.Clear();\r\n  " +
                    "                      param.Add(new SqlParameter(\"@ID\", activityBoardId));\r\n    " +
                    "                    param.Add(new SqlParameter(\"@ContentID\", contentId));\r\n     " +
                    "                   param.Add(new SqlParameter(\"@CategoryID\", model.ContentID ?? " +
                    "CategoryModel.測試用類別));\r\n                        param.Add(new SqlParameter(\"@Dis" +
                    "playRatio\", model.DisplayRatio));\r\n                        param.Add(new SqlPara" +
                    "meter(\"@PlayTime\", model.PlayTime));\r\n                        db.Database.Execut" +
                    "eSqlCommand(@\" \r\n                            INSERT INTO ActivityBoard(ID, Conte" +
                    "ntID, CategoryID, DisplayRatio, PlayTime)\r\n                            VALUES (@" +
                    "ID, @ContentID, @CategoryID, @DisplayRatio, @PlayTime);\",\r\n                     " +
                    "       param.ToArray());\r\n\r\n                        #endregion\r\n\r\n              " +
                    "          dbContextTransaction.Commit();\r\n                    }\r\n               " +
                    "     catch (Exception e)\r\n                    {\r\n                        logger." +
                    "Error(e);\r\n                        dbContextTransaction.Rollback();\r\n           " +
                    "             return false;\r\n                    }\r\n                    return tr" +
                    "ue;\r\n                }\r\n\t        }\r\n        }\r\n\r\n        public bool UpdateActiv" +
                    "ityBoard(");
            
            #line 91 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            using (");
            
            #line 93 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 93 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write("())\r\n            {\r\n                using (var dbContextTransaction = db.Database" +
                    ".BeginTransaction())\r\n                {\r\n                    try\r\n              " +
                    "      {\r\n                        #region Table Content\r\n\r\n                      " +
                    "  param.Add(new SqlParameter(\"@ID\", model.ContentID));\r\n                        " +
                    "param.Add(new SqlParameter(\"@Name\", model.Name));\r\n                        param" +
                    ".Add(new SqlParameter(\"@Description\", model.Description ?? (object)DBNull.Value)" +
                    ");\r\n                        param.Add(new SqlParameter(\"@OpenTime\", model.OpenTi" +
                    "me));\r\n                        param.Add(new SqlParameter(\"@CloseTime\", model.Cl" +
                    "oseTime));\r\n                        param.Add(new SqlParameter(\"@IsPublish\", mod" +
                    "el.IsPublic));\r\n                        param.Add(new SqlParameter(\"@Updater\", m" +
                    "odel.Updater ?? \"system\"));\r\n                        db.Database.ExecuteSqlComma" +
                    "nd(@\" \r\n                            UPDATE Content\r\n                            " +
                    "SET Name = @Name,\r\n                                IsPublish = @IsPublish, \r\n   " +
                    "                             Description = @Description,\r\n                      " +
                    "          OpenTime = @OpenTime,\r\n                                CloseTime = @Cl" +
                    "osetime,\r\n\t\t\t\t\t            Updater = @Updater, \r\n                               " +
                    " UpdateTime = GETDATE()\r\n                            WHERE ID = @ID;\",\r\n        " +
                    "                    param.ToArray());\r\n\r\n                        #endregion\r\n\r\n " +
                    "                       #region Table ActivityBoard\r\n\r\n                        pa" +
                    "ram.Clear();\r\n                        param.Add(new SqlParameter(\"@ID\", model.Co" +
                    "ntentID));\r\n                        param.Add(new SqlParameter(\"@CategoryID\", Ca" +
                    "tegoryModel.測試用類別));\r\n                        param.Add(new SqlParameter(\"@Displ" +
                    "ayRatio\", model.DisplayRatio));\r\n                        param.Add(new SqlParame" +
                    "ter(\"@PlayTime\", model.PlayTime));\r\n                        db.Database.ExecuteS" +
                    "qlCommand(@\" \r\n                            UPDATE ActivityBoard\r\n               " +
                    "             SET CategoryID = @CategoryID,\r\n                                Disp" +
                    "layRatio = @DisplayRatio, \r\n                                PlayTime = @PlayTime" +
                    "\r\n                            WHERE ID = @ID;\",\r\n                            par" +
                    "am.ToArray());\r\n\r\n                        #endregion\r\n\r\n                        " +
                    "#region Table FileUpload\r\n\r\n                        //刪除區域相關上傳檔案\r\n              " +
                    "          db.Database.ExecuteSqlCommand(@\" \r\n                            delete " +
                    "FileUpload\r\n                            where ContentID = @ContentID\",\r\n        " +
                    "                    new SqlParameter(\"@ContentID\", model.ContentID));\r\n         " +
                    "               if (model.PicUrl != null && !string.IsNullOrEmpty(model.PicUrl.Fi" +
                    "leName))\r\n                        {\r\n                            //新增照片\r\n       " +
                    "                     fileUploadDao.InsertFileUpload\r\n                           " +
                    "     (model.ContentID, FileUploadModel.上傳測試類別, model.Updater, model.PicUrl, db);" +
                    "\r\n                        }\r\n\r\n                        #endregion\r\n\r\n           " +
                    "             dbContextTransaction.Commit();\r\n                    }\r\n            " +
                    "        catch (Exception e)\r\n                    {\r\n                        logg" +
                    "er.Error(e);\r\n                        dbContextTransaction.Rollback();\r\n        " +
                    "                return false;\r\n                    }\r\n                }\r\n       " +
                    "         return true;\r\n            }\r\n        }\r\n\r\n        public bool DeleteAct" +
                    "ivityBoard(string id)\r\n        {\r\n            using(");
            
            #line 170 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 170 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write("())\r\n            {\r\n                using(var dbContextTransaction = db.Database." +
                    "BeginTransaction())\r\n\t            {\r\n\t\t            try\r\n                    {\r\n " +
                    "                       #region Get ContentID\r\n                        param.Add(" +
                    "new SqlParameter(\"@ID\", id));\r\n                        string contentId = db.Dat" +
                    "abase.SqlQuery<string>(@\" \r\n                            select ContentID\r\n      " +
                    "                      from ActivityBoard\r\n                            where ID =" +
                    " @ID;\",\r\n                        param.ToArray()).Single();\r\n                   " +
                    "     #endregion\r\n\r\n                        #region Drop all \r\n                  " +
                    "      param.Clear();\r\n                        param.Add(new SqlParameter(\"@Conte" +
                    "ntID\", contentId));\r\n                        param.Add(new SqlParameter(\"@ID\", i" +
                    "d));\r\n                        db.Database.ExecuteSqlCommand(@\"\r\n                " +
                    "            DELETE FileUpload WHERE ContentID = @ContentID;\r\n                   " +
                    "         DELETE ClickRecord WHERE ContentID = @ContentID;\r\n                     " +
                    "       DELETE ActivityBoard WHERE ID = @ID;\r\n                            DELETE " +
                    "Content WHERE ID = @ContentID;\r\n                            \",\r\n                " +
                    "            param.ToArray());\r\n                        #endregion\r\n             " +
                    "  \r\n                        dbContextTransaction.Commit();\r\n                    " +
                    "}\r\n                    catch (Exception e)\r\n                    {\r\n             " +
                    "           logger.Error(e);\r\n                        dbContextTransaction.Rollba" +
                    "ck();\r\n                        return false;\r\n                    }\r\n           " +
                    "     }\r\n\t        }\r\n            return true;\r\n        }\r\n\r\n        public List<");
            
            #line 211 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write("> GetAll()\r\n        {\r\n            List<");
            
            #line 213 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write("> colViewData = new List<");
            
            #line 213 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(">();\r\n            try\r\n            {\r\n                using (");
            
            #line 216 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 216 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(@"())
                {
                    #region 預設變數
                    StringBuilder sql = new StringBuilder();
                    #endregion

                    sql.AppendFormat(@""
		                    SELECT
			                    a.ID,
                                a.ContentID,
                                a.DisplayRatio,
                                a.PlayTime,
                                c.Name Category,
                                cnt.IsPublish IsPublic,
                                cnt.Name,
                                cnt.Description,
                                cnt.OpenTime,
                                cnt.CloseTime
		                    FROM ActivityBoard a 
                            inner join Content cnt on cnt.ID = ContentID
                            inner join Category c on c.ID = a.CategoryID
                            ORDER BY cnt.Name
	                    "");
                    colViewData = db.Database.SqlQuery<");
            
            #line 239 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(">(sql.ToString(), param.ToArray()).ToList();\r\n\r\n                    foreach (");
            
            #line 241 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(@" item in colViewData)
                    {
                        item.PicUrl = fileUploadDao.GetFileUploadByid(item.ID);
                    }
                }
            }
            catch (Exception e)
            {
                logger.Error(e);
                return null;
            }
            return colViewData;
        }

        public List<");
            
            #line 255 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write("> GetAll(PagenationModel model)\r\n        {\r\n            List<");
            
            #line 257 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write("> colViewData = new List<");
            
            #line 257 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(">();\r\n            try\r\n            {\r\n                using (");
            
            #line 260 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 260 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write("())\r\n                {\r\n                    #region 預設變數\r\n                    var" +
                    " min = 0;\r\n                    var max = 200000000;\r\n                    if (mod" +
                    "el != null)\r\n                    {\r\n                        min = (model.Page - " +
                    "1) * model.CntPerPage + 1;\r\n                        max = model.Page * model.Cnt" +
                    "PerPage;\r\n                        if (min >= max)\r\n                        {\r\n  " +
                    "                          min = 0;\r\n                            max = 20;\r\n     " +
                    "                   }\r\n                    }\r\n                    param.Add(new S" +
                    "qlParameter(\"@MIN\", min));\r\n                    param.Add(new SqlParameter(\"@MAX" +
                    "\", max));\r\n                    StringBuilder sql = new StringBuilder();\r\n       " +
                    "             #endregion\r\n                    \r\n                    #region 欄位排序用" +
                    "\r\n                    string[] colOrder = { \"cnt.UpdateTime\", \"cnt.Name\", \"c.Nam" +
                    "e\", \"cnt.OpenTime\", \"a.DisplayRatio\" };\r\n                    string orderTitle =" +
                    " (model != null && (colOrder.Length > model.OrderNum)) ? colOrder[model.OrderNum" +
                    "] : colOrder[0];\r\n                    string order = (model != null) ? (model.Or" +
                    "der ? \"ASC\" : \"DESC\") : \"ASC\";\r\n                    #endregion//\r\n\r\n            " +
                    "        #region 關鍵字篩選\r\n                    string condition = string.Empty;\r\n   " +
                    "                 List<string> lstWhere = new List<string>();\r\n\r\n                " +
                    "    //關鍵字搜尋\r\n                    if (model != null && !String.IsNullOrEmpty(mode" +
                    "l.KeyWord))\r\n                    {   //檢索分類\r\n                        if (model.Q" +
                    "ueryField == PagenationModel.測試用類別)\r\n                        {\r\n                " +
                    "            lstWhere.Add(\" cnt.Name LIKE @KeyWord ESCAPE \'\\\\\' \");\r\n             " +
                    "               param.Add(new SqlParameter(\"@KeyWord\", \"%\" + Regex.Replace(model." +
                    "KeyWord, @\"([\\[\\]\\%\\\\_])\", @\"\\$1\") + \"%\"));\r\n                        }\r\n        " +
                    "                else if (model.QueryField == PagenationModel.測試用類別2)\r\n          " +
                    "              {\r\n                            lstWhere.Add(\" c.Name LIKE @KeyWord" +
                    " ESCAPE \'\\\\\' \");\r\n                            param.Add(new SqlParameter(\"@KeyWo" +
                    "rd\", \"%\" + Regex.Replace(model.KeyWord, @\"([\\[\\]\\%\\\\_])\", @\"\\$1\") + \"%\"));\r\n    " +
                    "                    }\r\n\r\n                    }\r\n\r\n                    if (lstWhe" +
                    "re.Count > 0)\r\n                        condition = string.Format(\" WHERE {0} \", " +
                    "string.Join(\" AND \", lstWhere.ToArray()));\r\n                    #endregion\r\n\r\n  " +
                    "                  sql.AppendFormat(@\"\r\n\t                    select *\r\n\t         " +
                    "           from (\r\n\t\t                    SELECT\r\n\t\t\t                    a.ID,\r\n " +
                    "                               a.ContentID,\r\n                                a.D" +
                    "isplayRatio,\r\n                                a.PlayTime,\r\n                     " +
                    "           c.Name Category,\r\n                                cnt.IsPublish IsPub" +
                    "lic,\r\n                                cnt.Name,\r\n                               " +
                    " cnt.Description,\r\n                                cnt.OpenTime,\r\n              " +
                    "                  cnt.CloseTime,\r\n\t\t\t                    ROW_NUMBER() OVER ( ORD" +
                    "ER BY {0} {1} ) RN,\r\n                                COUNT(*) OVER () TotalNum\r\n" +
                    "\t\t                    FROM ActivityBoard a \r\n                            inner j" +
                    "oin Content cnt on cnt.ID = ContentID\r\n                            inner join Ca" +
                    "tegory c on c.ID = a.CategoryID\r\n                            {2}\r\n\t             " +
                    "       ) data\r\n                        WHERE RN BETWEEN @MIN AND @MAX ORDER BY R" +
                    "N\r\n\t                    \",\r\n                    orderTitle,\r\n                   " +
                    " order,\r\n                    condition);\r\n                    colViewData = db.D" +
                    "atabase.SqlQuery<");
            
            #line 336 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(">(sql.ToString(), param.ToArray()).ToList();\r\n\r\n                    foreach (");
            
            #line 338 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(@" item in colViewData) 
                    {
                        item.PicUrl = fileUploadDao.GetFileUploadByid(item.ID);
                    }
                }
            }
            catch (Exception e)
            {
                logger.Error(e);
                return null;
            }
            return colViewData;
        }

        public ");
            
            #line 352 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(" GetById(string Id)\r\n        {\r\n\r\n            ");
            
            #line 355 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(" colViewData = new ");
            
            #line 355 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write("();\r\n            try\r\n            {\r\n                using (");
            
            #line 358 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 358 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DataAccessContext));
            
            #line default
            #line hidden
            this.Write("())\r\n                {\r\n                    colViewData = db.Database.SqlQuery<");
            
            #line 360 "C:\Users\OI\Documents\git\Git\Csharp_in_Depth\T4_sample\CodeGenerator\Template\DLLTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ModelName));
            
            #line default
            #line hidden
            this.Write(@">(@""
                        SELECT
			                a.ID,
                            a.ContentID,
                            a.DisplayRatio,
                            a.PlayTime,
                            cnt.IsPublish IsPublic,
                            cnt.Name,
                            cnt.Description,
                            cnt.OpenTime,
                            cnt.CloseTime
		                FROM ActivityBoard a 
                        left join content cnt on cnt.ID = ContentID
                        WHERE a.ID = @ID""
                        , new SqlParameter(""@ID"", Id)).Single();

                    colViewData.PicUrl = fileUploadDao.GetFileUploadByid(Id);
                }
            }
            catch (Exception e)
            {
                logger.Error(e);
                return null;
            }
            return colViewData;
        }

        #endregion

    }
}

");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class DLLTempBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
